### ISSUE TITLE
node-cron not updated in package.json

### ISSUE THREAD

**Issue by noormohammedb** [Cyborg-Network/Worker#7]
https://github.com/Cyborg-Network/Worker/blob/553d11cc8efb60fd02c6c62e63a20a472d9b1d4f/KubeServiceUpdated.js#L8 node cron not updated in the `package.json` dependencies https://github.com/Cyborg-Network/Worker/blob/553d11cc8efb60fd02c6c62e63a20a472d9b1d4f/package.json#L21

**Comment by ZCalz** [comment]
updated in https://github.com/Cyborg-Network/Worker/commit/8ee974b3f9c8fb8cc64a494c2781ab68f9bdb50c
